title: Tài nguyên ngôn ngữ - Khu học mở
description: Kho lưu trữ cả đống tài nguyên immersion cho các chương trình học ngôn ngữ của Khu học mở
author: duykhanh471
theme: minima
nav_pages:
  - media-recs/tieng-anh/index.md
  - ngon-ngu/tieng-nhat/index.md
  - media-recs/tieng-viet/index.md
