title: Tài nguyên ngôn ngữ - Khu học mở
description: Kho lưu trữ cả đống tài nguyên immersion cho các chương trình học ngôn ngữ của Khu học mở
author: duykhanh471
theme: minima
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- media-recs/tieng-anh/index.html
- ngon-ngu/tieng-nhat/index.html
- media-recs/tieng-viet/index.html
